"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowUpRight, BookOpen, Check, ChevronLeft, Command, Copy, Github, Moon, Search, Sparkles, Star, Sun, TrendingUp, X } from "./icons";

type Skill={id:string;name:string;collection:string;source:string;categorySlug:string;categoryName:string;rank?:number;metricValue?:number;metricLabel?:string;summaryZh?:string;cardValueZh?:string;recommendationZh?:string;installCommand?:string;githubUrl?:string;tags?:string[];bestFor?:string[]};
type Category={slug:string;name:string;description?:string;availableCount?:number};
type Collection={slug:string;name:string;description?:string;skillIds?:string[]};
type Dataset={skills:Skill[];categories:Category[];collections?:Collection[];trending?:{skillId:string;reason?:string}[]};
type Route={view:"directory"|"skill"|"collection";id?:string};

const labels:Record<string,string>={all:"全部",install:"安装榜",community:"社区榜",qiaomu:"乔木库"};
const metric=(n?:number)=>!n?"—":n>=1e6?`${(n/1e6).toFixed(1)}m`:n>=1e3?`${(n/1e3).toFixed(n>1e4?0:1)}k`:String(n);
const parseRoute=():Route=>{const p=decodeURIComponent(location.pathname);if(p.startsWith("/skills/"))return{view:"skill",id:p.slice(8).replace(/\/$/,"")};if(p.startsWith("/collections/"))return{view:"collection",id:p.slice(13).replace(/\/$/,"")};return{view:"directory"}};
const hrefFor=(route:Route)=>route.view==="skill"?`/skills/${encodeURIComponent(route.id||"")}/`:route.view==="collection"?`/collections/${encodeURIComponent(route.id||"")}/`:"/";

function SkillCard({skill,onOpen}:{skill:Skill;onOpen:(s:Skill)=>void}){return <article className="skill-card"><button className="card-main" onClick={()=>onOpen(skill)} aria-label={`查看 ${skill.name}`}><div className="card-topline"><span className={`source-badge source-${skill.collection}`}>{labels[skill.collection]||skill.collection}</span><span className="rank"><TrendingUp size={14}/> #{skill.rank||"—"}</span></div><div><h3>{skill.name}</h3><p className="byline">{skill.source||"Open source"}</p></div><p className="description">{skill.cardValueZh||skill.summaryZh||"查看这个 Agent Skill 的用途、推荐理由和安装方式。"}</p></button><div className="card-footer"><span>{skill.categoryName}</span><strong><Star size={14}/> {metric(skill.metricValue)}</strong></div></article>}

export default function Home(){
 const [data,setData]=useState<Dataset|null>(null),[query,setQuery]=useState(""),[category,setCategory]=useState(()=>typeof window==="undefined"?"all":new URLSearchParams(location.search).get("category")||"all"),[source,setSource]=useState("all"),[sort,setSort]=useState("rank"),[route,setRoute]=useState<Route>(()=>typeof window==="undefined"?{view:"directory"}:parseRoute());
 const [dark,setDark]=useState(()=>typeof window!=="undefined"&&(localStorage.getItem("skill-theme")==="dark"||(!localStorage.getItem("skill-theme")&&matchMedia("(prefers-color-scheme: dark)").matches))),[copied,setCopied]=useState(false),[visibleCount,setVisibleCount]=useState(24),[loadError,setLoadError]=useState(false);
 const resultsRef=useRef<HTMLElement>(null),chipsRef=useRef<HTMLDivElement>(null);

 const navigate=useCallback((next:Route)=>{const target=next.view==="directory"&&category!=="all"?`/?category=${encodeURIComponent(category)}`:hrefFor(next);history.pushState({},"",target);setRoute(next);scrollTo({top:0,behavior:"smooth"})},[category]);

 useEffect(()=>{fetch("/data/skills.json").then(r=>{if(!r.ok)throw new Error();return r.json()}).then(setData).catch(()=>setLoadError(true));const pop=()=>{setRoute(parseRoute());setCategory(new URLSearchParams(location.search).get("category")||"all")};addEventListener("popstate",pop);return()=>removeEventListener("popstate",pop)},[]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light";localStorage.setItem("skill-theme",dark?"dark":"light")},[dark]);
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.key==="/"&&document.activeElement?.tagName!=="INPUT"){e.preventDefault();document.querySelector<HTMLInputElement>("#skill-search")?.focus()}if(e.key==="Escape"&&route.view!=="directory")navigate({view:"directory"})};addEventListener("keydown",fn);return()=>removeEventListener("keydown",fn)},[navigate,route.view]);

 const selectCategory=(slug:string)=>{setCategory(slug);setVisibleCount(24);const params=new URLSearchParams(location.search);if(slug==="all")params.delete("category");else params.set("category",slug);history.replaceState({},"",`/${params.size?`?${params}`:""}`);requestAnimationFrame(()=>{resultsRef.current?.scrollIntoView({behavior:"smooth",block:"start"});chipsRef.current?.querySelector<HTMLElement>(`[data-category="${CSS.escape(slug)}"]`)?.scrollIntoView({behavior:"smooth",inline:"center",block:"nearest"})})};
 const clearFilters=()=>{setQuery("");setCategory("all");setSource("all");setSort("rank");setVisibleCount(24);history.replaceState({},"","/")};
 const copy=async(skill:Skill)=>{await navigator.clipboard.writeText(skill.installCommand||`npx skills add ${skill.name}`);setCopied(true);setTimeout(()=>setCopied(false),1600)};

 const filtered=useMemo(()=>data?data.skills.filter(s=>category==="all"||s.categorySlug===category).filter(s=>source==="all"||s.collection===source).filter(s=>!query.trim()||[s.name,s.source,s.cardValueZh,s.summaryZh,s.categoryName,...(s.tags||[])].join(" ").toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):(a.rank||9999)-(b.rank||9999)):[],[data,query,category,source,sort]);
 const trending=useMemo(()=>data?(data.trending||[]).map(x=>data.skills.find(s=>s.id===x.skillId)).filter(Boolean).slice(0,6) as Skill[]:[],[data]);
 const selectedSkill=data?.skills.find(s=>s.id===route.id);
 const selectedCollection=data?.collections?.find(c=>c.slug===route.id);
 const collectionSkills=selectedCollection?data?.skills.filter(s=>selectedCollection.skillIds?.includes(s.id))||[]:[];
 const activeCategory=data?.categories.find(c=>c.slug===category);

 if(loadError)return <div className="fatal-state"><Command/><h1>目录暂时没有载入</h1><p>请刷新页面重试。</p><button onClick={()=>location.reload()}>重新载入</button></div>;
 if(!data)return <div className="loading"><span className="brand-mark">SK</span><p>正在整理 Skill 目录…</p></div>;

 return <><a className="skip-link" href="#main-content">跳到主要内容</a><header className="site-header"><button className="brand" onClick={()=>{setCategory("all");history.pushState({},"","/");setRoute({view:"directory"});scrollTo({top:0,behavior:"smooth"})}} aria-label="Skill 推荐网首页"><span className="brand-mark">SK</span><span className="brand-text"><strong>Skill 推荐网</strong><small>Agent skills, curated.</small></span></button><nav className="header-actions" aria-label="主导航"><button className="header-link" onClick={()=>{navigate({view:"directory"});setTimeout(()=>document.querySelector("#collections")?.scrollIntoView({behavior:"smooth"}),60)}}>专题合集</button><a className="header-link" href="https://github.com/joeseesun/" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={13}/></a><button className="icon-button" onClick={()=>setDark(!dark)} aria-label={dark?"切换到浅色模式":"切换到深色模式"}>{dark?<Sun/>:<Moon/>}</button></nav></header>
 <main className="app-shell" id="main-content">{route.view==="skill"&&selectedSkill?<SkillDetail skill={selectedSkill} copy={()=>copy(selectedSkill)} copied={copied} back={()=>history.length>1?history.back():navigate({view:"directory"})} related={data.skills.filter(s=>s.id!==selectedSkill.id&&s.categorySlug===selectedSkill.categorySlug).slice(0,4)} open={s=>navigate({view:"skill",id:s.id})}/>:
 route.view==="collection"&&selectedCollection?<CollectionDetail collection={selectedCollection} skills={collectionSkills} back={()=>history.length>1?history.back():navigate({view:"directory"})} open={s=>navigate({view:"skill",id:s.id})}/>:
 route.view!=="directory"?<div className="fatal-state"><Command/><h1>这个页面不存在</h1><p>条目可能已经移动或被移除。</p><button onClick={()=>navigate({view:"directory"})}>返回全部 Skill</button></div>:
 <><section className="hero"><div className="hero-copy"><p className="eyebrow"><Sparkles size={14}/> Agent Skills Directory · 2026</p><h1>发现更好用的<br/><span>Agent Skills</span></h1><p className="lead">把公开榜单、社区口碑和 GitHub 原文整理成真正能读懂的中文目录。先判断用途，再看热度，最后一键安装。</p></div><div className="hero-aside"><p>已收录</p><strong>{data.skills.length}</strong><span>个经过整理的 Skill</span><div className="source-tally"><span>{data.categories.length} 分类</span><span>{data.collections?.length||0} 专题</span></div></div></section>
 <section className="filter-dock" aria-label="搜索与筛选"><div className="search-box"><Search size={19}/><input id="skill-search" value={query} onChange={e=>{setQuery(e.target.value);setVisibleCount(24)}} placeholder="搜索 Skill、作者或使用场景…" aria-label="搜索 Skill"/><span className="search-count">{filtered.length} 个结果</span>{query?<button onClick={()=>{setQuery("");setVisibleCount(24)}} aria-label="清除搜索"><X size={17}/></button>:<kbd>/</kbd>}</div><div className="chips-row" ref={chipsRef}><button data-category="all" className={category==="all"?"active":""} onClick={()=>selectCategory("all")}>全部 <span>{data.skills.length}</span></button>{data.categories.map(c=><button data-category={c.slug} key={c.slug} className={category===c.slug?"active":""} onClick={()=>selectCategory(c.slug)}>{c.name} <span>{c.availableCount}</span></button>)}</div><div className="dock-filters"><div className="segmented" aria-label="榜单来源">{Object.entries(labels).map(([k,v])=><button key={k} className={source===k?"active":""} aria-pressed={source===k} onClick={()=>{setSource(k);setVisibleCount(24)}}>{v}</button>)}</div><label>排序 <select value={sort} onChange={e=>{setSort(e.target.value);setVisibleCount(24)}}><option value="rank">按热度</option><option value="name">按名称</option></select></label></div></section>
 {!!trending.length&&<section className="strip-panel"><div className="section-head"><div><p className="eyebrow">Trending now</p><h2>近期值得关注</h2></div><p>从近期安装变化与社区热度中精选。</p></div><div className="trending-strip">{trending.map((s,i)=><button key={s.id} onClick={()=>navigate({view:"skill",id:s.id})}><span>0{i+1}</span><div><strong>{s.name}</strong><small>{s.categoryName}</small></div><ArrowUpRight/></button>)}</div></section>}
 {!!data.collections?.length&&<section className="collections-panel" id="collections"><div className="section-head"><div><p className="eyebrow">Curated collections</p><h2>从任务出发的专题合集</h2></div><p>不再逐个挑选，把一条完整工作流所需的 Skill 放在一起。</p></div><div className="collections-strip">{data.collections.slice(0,6).map((c,i)=><button key={c.slug} onClick={()=>navigate({view:"collection",id:c.slug})}><span className="collection-index">0{i+1}</span><span className="collection-icon"><BookOpen/></span><div><small>专题合集</small><h3>{c.name}</h3><p>{c.description}</p></div><strong>{c.skillIds?.length||0} SKILLS <ArrowUpRight size={14}/></strong></button>)}</div><button className="all-collections" onClick={()=>navigate({view:"collection",id:data.collections?.[6]?.slug||data.collections?.[0]?.slug})}>继续探索更多专题 <ArrowUpRight size={15}/></button></section>}
 <section className="results-panel" ref={resultsRef}><div className="results-head"><div><p className="eyebrow">{labels[source]} · {filtered.length} results</p><h2>{activeCategory?.name||"全部 Skill"}</h2><p>{activeCategory?.description||"按综合热度排列，点击卡片查看推荐理由和安装方式。"}</p></div>{(query||category!=="all"||source!=="all"||sort!=="rank")&&<button className="reset-button" onClick={clearFilters}><X size={14}/> 清除筛选</button>}</div><div className="skill-grid">{filtered.slice(0,visibleCount).map(s=><SkillCard key={s.id} skill={s} onOpen={s=>navigate({view:"skill",id:s.id})}/>)}</div>{filtered.length>visibleCount&&<button className="load-more" onClick={()=>setVisibleCount(n=>n+24)}>加载更多 <span>{visibleCount} / {filtered.length}</span></button>}{!filtered.length&&<div className="empty-state"><Command/><h3>没有找到匹配项</h3><p>换一个关键词，或清除当前筛选条件。</p><button onClick={clearFilters}>查看全部 Skill</button></div>}</section></>}</main>
 <footer><div><span className="brand-mark">SK</span><p><strong>Skill 推荐网</strong><br/>每一个条目都打开过原文，值得不值得装，看完再定。</p></div><p>数据来自公开页面与 GitHub 原始文档<br/>指标以公开展示为准</p></footer></>;
}

function SkillDetail({skill,copy,copied,back,related,open}:{skill:Skill;copy:()=>void;copied:boolean;back:()=>void;related:Skill[];open:(s:Skill)=>void}){return <article className="detail-view"><button className="back-button" onClick={back}><ChevronLeft size={17}/> 返回目录</button><div className="detail-hero"><div><div className="detail-kicker"><span className={`source-badge source-${skill.collection}`}>{labels[skill.collection]}</span><span>{skill.categoryName}</span><span>{skill.source}</span></div><h1>{skill.name}</h1><p>{skill.cardValueZh||skill.summaryZh}</p></div><div className="detail-rank"><small>热度排名</small><strong>#{skill.rank||"—"}</strong><span><Star size={15}/> {metric(skill.metricValue)} {skill.metricLabel}</span></div></div><div className="detail-grid"><section className="prose-card"><p className="eyebrow">Editorial note</p><h2>为什么值得装</h2><p>{skill.recommendationZh||skill.summaryZh}</p><div className="tag-list">{(skill.tags||skill.bestFor||[skill.categoryName]).map(t=><span key={t}>{t}</span>)}</div></section><aside className="install-card"><p className="eyebrow">Quick install</p><h2>复制后即可安装</h2><button className="command-box" onClick={copy}><code>{skill.installCommand||`npx skills add ${skill.name}`}</code>{copied?<Check size={18}/>:<Copy size={18}/>}</button>{skill.githubUrl&&<a className="primary-link" href={skill.githubUrl} target="_blank" rel="noreferrer"><Github size={17}/> 查看原始文档 <ArrowUpRight size={15}/></a>}</aside></div>{!!related.length&&<section className="related-section"><div className="section-head"><div><p className="eyebrow">Keep exploring</p><h2>同类 Skill</h2></div></div><div className="skill-grid">{related.map(s=><SkillCard key={s.id} skill={s} onOpen={open}/>)}</div></section>}</article>}
function CollectionDetail({collection,skills,back,open}:{collection:Collection;skills:Skill[];back:()=>void;open:(s:Skill)=>void}){return <article className="collection-view"><button className="back-button" onClick={back}><ChevronLeft size={17}/> 返回目录</button><div className="collection-hero"><p className="eyebrow"><BookOpen size={14}/> Curated collection</p><h1>{collection.name}</h1><p>{collection.description}</p><span>{skills.length} 个 Skill · 按建议使用顺序排列</span></div><div className="collection-list">{skills.map((s,i)=><button key={s.id} onClick={()=>open(s)}><span>{String(i+1).padStart(2,"0")}</span><div><small>{s.categoryName}</small><h2>{s.name}</h2><p>{s.cardValueZh||s.summaryZh}</p></div><ArrowUpRight/></button>)}</div></article>}
