"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, BookOpen, Check, ChevronLeft, Command, Copy, Github, Moon, Search, Sparkles, Star, Sun, TrendingUp, X } from "./icons";

type Skill={id:string;name:string;collection:string;source:string;categorySlug:string;categoryName:string;author?:string;rank?:number;metricValue?:number;descriptionZh?:string;summaryZh?:string;cardValueZh?:string;recommendationZh?:string;installCommand?:string;repositoryUrl?:string;sourceUrl?:string;githubUrl?:string;tags?:string[];bestFor?:string[]};
type Dataset={skills:Skill[];categories:{slug:string;name:string}[];collections?:{slug:string;name:string;description?:string;skillIds?:string[]}[];trending?:{skillId:string;reason?:string}[]};
const labels:Record<string,string>={all:"全部榜单",install:"安装榜",community:"社区榜",qiaomu:"乔木库"};
const metric=(n?:number)=>!n?"—":n>=1e6?`${(n/1e6).toFixed(1)}m`:n>=1e3?`${(n/1e3).toFixed(n>1e4?0:1)}k`:String(n);

function SkillCard({skill,open}:{skill:Skill;open:(s:Skill)=>void}){return <button className="skill-card" onClick={()=>open(skill)}><div className="card-topline"><span className={`source-badge source-${skill.collection}`}>{labels[skill.collection]||skill.collection}</span><span className="rank"><TrendingUp size={14}/> #{skill.rank||"—"}</span></div><div><h3>{skill.name}</h3><p className="byline">{skill.source||"Open source"}</p></div><p className="description">{skill.cardValueZh||skill.summaryZh||"查看这个 Agent Skill 的用途、推荐理由和安装方式。"}</p><div className="card-footer"><span>{skill.categoryName}</span><strong><Star size={14}/> {metric(skill.metricValue)}</strong></div></button>}

export default function Home(){
 const [data,setData]=useState<Dataset|null>(null),[query,setQuery]=useState(""),[category,setCategory]=useState("all"),[source,setSource]=useState("all"),[sort,setSort]=useState("rank");
 const [dark,setDark]=useState(false),[detail,setDetail]=useState<Skill|null>(null),[copied,setCopied]=useState(false);
 useEffect(()=>{fetch("/data/skills.json").then(r=>r.json()).then(setData);const saved=localStorage.getItem("skill-theme");setDark(saved==="dark"||(!saved&&matchMedia("(prefers-color-scheme: dark)").matches))},[]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light";localStorage.setItem("skill-theme",dark?"dark":"light")},[dark]);
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.key==="/"&&document.activeElement?.tagName!=="INPUT"){e.preventDefault();document.querySelector<HTMLInputElement>("#skill-search")?.focus()}if(e.key==="Escape")setDetail(null)};addEventListener("keydown",fn);return()=>removeEventListener("keydown",fn)},[]);
 const visible=useMemo(()=>data?data.skills.filter(s=>category==="all"||s.categorySlug===category).filter(s=>source==="all"||s.collection===source).filter(s=>!query.trim()||[s.name,s.source,s.cardValueZh,s.summaryZh,s.categoryName,...(s.tags||[])].join(" ").toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):(a.rank||9999)-(b.rank||9999)):[],[data,query,category,source,sort]);
 const trending=useMemo(()=>data?(data.trending||[]).map(x=>data.skills.find(s=>s.id===x.skillId)).filter(Boolean).slice(0,6) as Skill[]:[],[data]);
 const copy=async()=>{if(!detail)return;await navigator.clipboard.writeText(detail.installCommand||`npx skills add ${detail.repositoryUrl||detail.name}`);setCopied(true);setTimeout(()=>setCopied(false),1600)};
 if(!data)return <div className="loading"><span className="brand-mark">SK</span><p>正在整理 Skill 目录…</p></div>;
 return <><header className="site-header"><button className="brand" onClick={()=>{setDetail(null);setCategory("all")}}><span className="brand-mark">SK</span><span className="brand-text"><strong>Skill 推荐网</strong><small>Agent skills, curated.</small></span></button><nav className="header-actions"><a className="header-link" href="#collections">专题合集</a><a className="header-link" href="https://github.com/joeseesun/" target="_blank">GitHub <ArrowUpRight size={13}/></a><button className="icon-button" onClick={()=>setDark(!dark)} aria-label="切换主题">{dark?<Sun/>:<Moon/>}</button></nav></header>
 <main className="app-shell">{detail?<article className="detail-view"><button className="back-button" onClick={()=>setDetail(null)}><ChevronLeft size={17}/> 返回目录</button><div className="detail-hero"><div><div className="detail-kicker"><span className={`source-badge source-${detail.collection}`}>{labels[detail.collection]}</span><span>{detail.categoryName}</span></div><h1>{detail.name}</h1><p>{detail.cardValueZh||detail.summaryZh}</p></div><div className="detail-rank"><small>热度排名</small><strong>#{detail.rank||"—"}</strong><span><Star size={15}/> {metric(detail.metricValue)}</span></div></div><div className="detail-grid"><section className="prose-card"><p className="eyebrow">为什么推荐</p><h2>先看值不值得装</h2><p>{detail.recommendationZh||detail.summaryZh}</p><div className="tag-list">{(detail.tags||detail.bestFor||[detail.categoryName]).map(t=><span key={t}>{t}</span>)}</div></section><aside className="install-card"><p className="eyebrow">Quick install</p><h2>安装 Skill</h2><button className="command-box" onClick={copy}><code>{detail.installCommand||`npx skills add ${detail.repositoryUrl||detail.name}`}</code>{copied?<Check size={18}/>:<Copy size={18}/>}</button>{(detail.githubUrl||detail.sourceUrl||detail.repositoryUrl)&&<a className="primary-link" href={detail.githubUrl||detail.sourceUrl||detail.repositoryUrl} target="_blank"><Github size={17}/> 查看原始文档 <ArrowUpRight size={15}/></a>}</aside></div></article>:
 <><section className="hero"><div className="hero-copy"><p className="eyebrow"><Sparkles size={14}/> Agent Skills Directory</p><h1><span>{data.skills.length}</span> 个 Skill，<br/>总有一个顺手</h1><p className="lead">从公开榜单和 GitHub 原文里挑出来的 Agent 技能：先看用途，再看热度，装上就用。</p></div><dl className="stats-row"><div><dt>{data.categories.length}</dt><dd>精选分类</dd></div><div><dt>{data.skills.filter(s=>s.collection==="install").length}</dt><dd>安装榜</dd></div><div><dt>{data.collections?.length||0}</dt><dd>专题合集</dd></div></dl></section>
 <section className="filter-dock"><div className="search-box"><Search size={19}/><input id="skill-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索 skill、作者或使用场景…"/>{query?<button onClick={()=>setQuery("")}><X size={17}/></button>:<kbd>/</kbd>}</div><div className="chips-row"><button className={category==="all"?"active":""} onClick={()=>setCategory("all")}>全部</button>{data.categories.map(c=><button key={c.slug} className={category===c.slug?"active":""} onClick={()=>setCategory(c.slug)}>{c.name}</button>)}</div><div className="dock-filters"><div className="segmented">{Object.entries(labels).map(([k,v])=><button key={k} className={source===k?"active":""} onClick={()=>setSource(k)}>{v.replace("榜单","")}</button>)}</div><label>排序 <select value={sort} onChange={e=>setSort(e.target.value)}><option value="rank">按热度</option><option value="name">按名称</option></select></label></div></section>
 {!!trending.length&&<section className="strip-panel"><div className="section-head"><div><p className="eyebrow">Trending now</p><h2>近期值得关注</h2></div><p>按近期安装变化与社区热度滚动生成。</p></div><div className="trending-strip">{trending.map((s,i)=><button key={s.id} onClick={()=>setDetail(s)}><span>0{i+1}</span><div><strong>{s.name}</strong><small>{s.categoryName}</small></div><ArrowUpRight/></button>)}</div></section>}
 {!!data.collections?.length&&<section className="collections-panel" id="collections"><div className="section-head"><div><p className="eyebrow">Collections</p><h2>专题合集</h2></div><p>把同一类任务会连续用到的 Skill 放在一起。</p></div><div className="collections-strip">{data.collections.map((c,i)=><button key={c.slug} onClick={()=>{const s=data.skills.find(x=>c.skillIds?.includes(x.id));if(s)setDetail(s)}}><span className="collection-icon"><BookOpen/></span><div><small>专题 {String(i+1).padStart(2,"0")}</small><h3>{c.name}</h3><p>{c.description}</p></div><strong>{c.skillIds?.length||0} SKILLS</strong></button>)}</div></section>}
 <section className="results-panel"><div className="results-head"><div><p className="eyebrow">{labels[source]}</p><h2>{category==="all"?"全部 Skill":data.categories.find(c=>c.slug===category)?.name}</h2></div><p>找到 <strong>{visible.length}</strong> 个结果</p></div><div className="skill-grid">{visible.map(s=><SkillCard key={s.id} skill={s} open={setDetail}/>)}</div>{!visible.length&&<div className="empty-state"><Command/><h3>没有找到匹配项</h3><p>换一个关键词或清除筛选试试。</p></div>}</section></>}</main>
 <footer><div><span className="brand-mark">SK</span><p>每一个条目都打开过原文，值得不值得装，看完再定。</p></div><p>数据来自公开页面与 GitHub 原始文档。</p></footer></>;
}
